/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package medafighter.vistas;

import java.io.File;
import java.io.IOException;
import java.io.PrintWriter;
import java.sql.SQLException;
import java.util.Vector;
import javax.swing.JFileChooser;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import medafighter.modelo.ConexionBD;
import medafighter.otros.MyTableModel;

/**
 *
 * @author Fabián
 */
public class DialogRecords extends javax.swing.JDialog {
    
    private ConexionBD cbd;

    /**
     * Creates new form DialogRecords
     */
    public DialogRecords(java.awt.Frame parent, boolean modal) throws SQLException {
        
        super(parent, modal);
        
        initComponents();
        
        this.cbd = new ConexionBD();
        
        Vector<Vector<Object>> datosJugador = new Vector<Vector<Object>>();
        
        datosJugador = this.cbd.buscarVDTJugadores();
        
        Vector<String> nombresColumnas = new Vector<String>();
        
        nombresColumnas.add("Jugador");
        nombresColumnas.add("Tipo");
        nombresColumnas.add("Victorias");
        nombresColumnas.add("Derrotas");
        nombresColumnas.add("Torneos");
        
        MyTableModel modeloTabla = new MyTableModel(datosJugador,nombresColumnas);
        
        this.tablaJugadores.setModel(modeloTabla);
        
        this.tablaJugadores.setAutoCreateRowSorter(true);
                
        this.setLocationRelativeTo(null);
        
        this.setVisible(true);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaJugadores = new javax.swing.JTable();
        guardarTxt = new javax.swing.JButton();
        volver = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jugador = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("MedaFighter - Records");
        setResizable(false);

        jLabel1.setText("Puede buscar el jugador cuyo record desea consultar y también guardar los");

        tablaJugadores.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Jugador", "Tipo", "Victorias", "Derrotas", "Torneos"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tablaJugadores);

        guardarTxt.setText("Guardar en archivo de texto");
        guardarTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guardarTxtActionPerformed(evt);
            }
        });

        volver.setText("Volver");
        volver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                volverActionPerformed(evt);
            }
        });

        jLabel2.setText("datos en un archivo de texto (tiene que agregar la extensión .txt al guardar).");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 384, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jugador, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(77, 77, 77)
                        .addComponent(guardarTxt)
                        .addGap(54, 54, 54)
                        .addComponent(volver)))
                .addContainerGap(41, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(jugador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(guardarTxt)
                    .addComponent(volver))
                .addGap(32, 32, 32))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void guardarTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guardarTxtActionPerformed
        
        JFileChooser jfc = new JFileChooser();
        
        int returnVal = jfc.showSaveDialog(this);
        
        if (returnVal == jfc.APPROVE_OPTION) {

            try {

                File file = jfc.getSelectedFile();

                PrintWriter pw = new PrintWriter(file);

                pw.println("");

                for (int row = 0; row < this.tablaJugadores.getRowCount(); row++) {

                    for (int col = 0; col < this.tablaJugadores.getColumnCount(); col++) {

                        pw.print(this.tablaJugadores.getColumnName(col));

                        pw.print(": ");

                        pw.println(this.tablaJugadores.getValueAt(row, col));

                    }

                }

                pw.close();

            } 

            catch (IOException e) {

                e.printStackTrace();

            }

        }        

        //JOptionPane.showMessageDialog(this, "¡Pronto en funcionamiento!");
        
    }//GEN-LAST:event_guardarTxtActionPerformed

    private void volverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_volverActionPerformed
        
        this.setVisible(false);
                
        this.dispose();
        
    }//GEN-LAST:event_volverActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton guardarTxt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jugador;
    private javax.swing.JTable tablaJugadores;
    private javax.swing.JButton volver;
    // End of variables declaration//GEN-END:variables
}
