/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package medafighter.vistas;

import java.awt.event.ActionListener;

/**
 *
 * @author Fabián
 */
public class VistaRegistro extends javax.swing.JFrame {

    /**
     * Creates new form VistaRegistro
     */
    public VistaRegistro(ActionListener al) {
        
        initComponents();
        
        this.setLocationRelativeTo(null);
        
        this.setVisible(true);
        
        agregarListener(al);
        
    }
    
    // Agrega listeners a los botones
    
    void agregarListener(ActionListener al){
        
        this.registrarse.addActionListener(al);
        
        this.volver.addActionListener(al);
        
    }    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        registrarse = new javax.swing.JButton();
        volver = new javax.swing.JButton();
        nombreUsuarioLabel = new javax.swing.JLabel();
        contraseniaLabel = new javax.swing.JLabel();
        nombreUsuarioTF = new javax.swing.JTextField();
        ingreseDatosLabel = new javax.swing.JLabel();
        contraseniaTF = new javax.swing.JPasswordField();
        nombreMedabotTF = new javax.swing.JTextField();
        nombreMedabotLabel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("MedaFighter - Registro");
        setResizable(false);

        registrarse.setText("Registrarse");

        volver.setText("Volver");

        nombreUsuarioLabel.setText("Nombre de Usuario");

        contraseniaLabel.setText("Contraseña");

        ingreseDatosLabel.setText("Ingrese sus datos en los siguientes campos");

        nombreMedabotLabel.setText("Nombre de Medabot");

        jLabel1.setText("(entre 4 y 15 caracteres)");

        jLabel2.setText("(entre 6 y 15 caracteres)");

        jLabel3.setText("(entre 4 y 15 caracteres)");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(83, 83, 83)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ingreseDatosLabel)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nombreUsuarioLabel)
                            .addComponent(contraseniaLabel)
                            .addComponent(nombreMedabotLabel))
                        .addGap(40, 40, 40)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nombreMedabotTF, javax.swing.GroupLayout.DEFAULT_SIZE, 141, Short.MAX_VALUE)
                            .addComponent(contraseniaTF)
                            .addComponent(nombreUsuarioTF))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1))
                .addGap(38, 38, 38))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(registrarse)
                .addGap(41, 41, 41)
                .addComponent(volver)
                .addGap(159, 159, 159))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addComponent(ingreseDatosLabel)
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nombreUsuarioLabel)
                    .addComponent(nombreUsuarioTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(contraseniaLabel)
                    .addComponent(contraseniaTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nombreMedabotTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nombreMedabotLabel)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(registrarse)
                    .addComponent(volver))
                .addGap(45, 45, 45))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // getters
    
    public javax.swing.JButton getRegistrarse(){
        return this.registrarse;
    }
    
    public javax.swing.JButton getVolver(){
        return this.volver;
    }
    
    public javax.swing.JTextField getNombreUsuario(){
        return this.nombreUsuarioTF;
    }
    
    public javax.swing.JPasswordField getContrasenia(){
        return this.contraseniaTF;
    }
        
    public javax.swing.JTextField getNombreMedabot(){
        return this.nombreMedabotTF;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel contraseniaLabel;
    private javax.swing.JPasswordField contraseniaTF;
    private javax.swing.JLabel ingreseDatosLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel nombreMedabotLabel;
    private javax.swing.JTextField nombreMedabotTF;
    private javax.swing.JLabel nombreUsuarioLabel;
    private javax.swing.JTextField nombreUsuarioTF;
    private javax.swing.JButton registrarse;
    private javax.swing.JButton volver;
    // End of variables declaration//GEN-END:variables
}
