/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package medafighter.vistas;

/* Clases importadas */

import java.awt.event.ActionListener;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import medafighter.modelo.ConexionBD;

/**
 *
 * @author Fabián
 */
public class VistaPrevia extends javax.swing.JFrame {
    
    private ConexionBD cbd;

    /**
     * Creates new form VistaPrevia
     */
    public VistaPrevia(ActionListener al) {
                
        initComponents();
        
        this.setLocationRelativeTo(null);
        
        this.cbd = new ConexionBD();
        
        ArrayList<String> jugadoresHumanos = new ArrayList<>();
            
        try {
            
            jugadoresHumanos = cbd.buscarJugadoresTipo("HUMANO");
            
        } 
            
        catch (SQLException ex) {
            
            Logger.getLogger(VistaPrevia.class.getName()).log(Level.SEVERE, null, ex);
            
        }
            
        String[] arrayJugadoresHumanos;
            
        arrayJugadoresHumanos = jugadoresHumanos.toArray(new String[100]);
            
        jugador1L.setListData(arrayJugadoresHumanos);
            
        jugador2L.setListData(arrayJugadoresHumanos);
        
        this.setVisible(true);
        
        agregarListener(al);       
        
    }
    
    void agregarListener(ActionListener al){
        
        this.robobatalla.addActionListener(al);
        
        this.volver.addActionListener(al);
        
        this.records.addActionListener(al);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        queRobobatallaLabel = new javax.swing.JLabel();
        modoJuegoLabel = new javax.swing.JLabel();
        modoJuegoCB = new javax.swing.JComboBox();
        jugadoresLabel = new javax.swing.JLabel();
        jugador1SP = new javax.swing.JScrollPane();
        jugador1L = new javax.swing.JList();
        jugador2SP = new javax.swing.JScrollPane();
        jugador2L = new javax.swing.JList();
        robobatalla = new javax.swing.JButton();
        volver = new javax.swing.JButton();
        records = new javax.swing.JButton();
        medabotJ1 = new javax.swing.JComboBox();
        medabotJ2 = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("MedaFighter - Previa Medabatalla");
        setResizable(false);

        queRobobatallaLabel.setText("¿Qué clase de robobatalla desea?");

        modoJuegoLabel.setText("Modo de juego");

        modoJuegoCB.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Jugador v/s Jugador", "Jugador v/s CPU", "CPU V/S CPU" }));
        modoJuegoCB.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                modoJuegoCBItemStateChanged(evt);
            }
        });

        jugadoresLabel.setText("Jugadores");

        jugador1L.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jugador1SP.setViewportView(jugador1L);

        jugador2L.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jugador2SP.setViewportView(jugador2L);

        robobatalla.setText("Robobatalla!");

        volver.setText("Volver");

        records.setText("Ver Records");

        medabotJ1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Version 1", "Version 2", "Version 3" }));

        medabotJ2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Version 1", "Version 2", "Version 3" }));

        jLabel1.setText("Medabot");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(robobatalla)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(volver)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(records)
                .addGap(65, 65, 65))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(modoJuegoLabel)
                            .addComponent(jugadoresLabel)
                            .addComponent(jLabel1))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(modoJuegoCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jugador1SP, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(medabotJ1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(medabotJ2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jugador2SP, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(117, 117, 117)
                        .addComponent(queRobobatallaLabel)))
                .addContainerGap(36, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(queRobobatallaLabel)
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(modoJuegoLabel)
                            .addComponent(modoJuegoCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(36, 36, 36)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(jugador1SP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jugador2SP, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(149, 149, 149)
                        .addComponent(jugadoresLabel)))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(medabotJ1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(medabotJ2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(robobatalla)
                    .addComponent(volver)
                    .addComponent(records))
                .addGap(28, 28, 28))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void modoJuegoCBItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_modoJuegoCBItemStateChanged
        
        String modoJuego = (String)modoJuegoCB.getSelectedItem();
        
        this.cbd = new ConexionBD();
        
        if(modoJuego.equals("Jugador v/s Jugador")){
            
            ArrayList<String> jugadoresHumanos = new ArrayList<>();
            
            try {
            
                jugadoresHumanos = cbd.buscarJugadoresTipo("HUMANO");
            
            } 
            
            catch (SQLException ex) {
            
                Logger.getLogger(VistaPrevia.class.getName()).log(Level.SEVERE, null, ex);
            
            }
            
            String[] arrayJugadoresHumanos;
            
            arrayJugadoresHumanos = jugadoresHumanos.toArray(new String[100]);
            
            jugador1L.setListData(arrayJugadoresHumanos);
            
            jugador2L.setListData(arrayJugadoresHumanos);
            
            String[] arrayMedabots = new String[3];
            
            arrayMedabots[0] = "Version 1";
            
            arrayMedabots[1] = "Version 2";
            
            arrayMedabots[2] = "Version 3";
            
            DefaultComboBoxModel modeloMedabots = new DefaultComboBoxModel(arrayMedabots);
            
            medabotJ1.setModel(modeloMedabots);
            
            medabotJ2.setModel(modeloMedabots);
            
        }
        
        if(modoJuego.equals("Jugador v/s CPU")){
            
            ArrayList<String> jugadoresHumanos = new ArrayList<>();
            ArrayList<String> jugadoresCPU = new ArrayList<>();
            
            try {
            
                jugadoresHumanos = cbd.buscarJugadoresTipo("HUMANO");
                jugadoresCPU = cbd.buscarJugadoresTipo("CPU");
            
            } 
            
            catch (SQLException ex) {
            
                Logger.getLogger(VistaPrevia.class.getName()).log(Level.SEVERE, null, ex);
            
            }
            
            String[] arrayJugadoresHumanos;
            
            String[] arrayJugadoresCPU;
            
            arrayJugadoresHumanos = jugadoresHumanos.toArray(new String[100]);
            
            arrayJugadoresCPU = jugadoresCPU.toArray(new String[100]);
            
            jugador1L.setListData(arrayJugadoresHumanos);
            
            jugador2L.setListData(arrayJugadoresCPU);
            
            String[] arrayMedabotsJ1 = new String[3];
            
            String[] arrayMedabotsJ2 = new String[1];
            
            arrayMedabotsJ1[0] = "Version 1";
            
            arrayMedabotsJ1[1] = "Version 2";
            
            arrayMedabotsJ1[2] = "Version 3";
            
            arrayMedabotsJ2[0] = "Version 1";
            
            DefaultComboBoxModel modeloMedabotsJ1 = new DefaultComboBoxModel(arrayMedabotsJ1);
            
            medabotJ2.setModel(modeloMedabotsJ1);
            
            DefaultComboBoxModel modeloMedabotsJ2 = new DefaultComboBoxModel(arrayMedabotsJ2);
            
            medabotJ2.setModel(modeloMedabotsJ2);
            
        }
        
        if(modoJuego.equals("CPU V/S CPU")){
            
            ArrayList<String> jugadoresCPU = new ArrayList<>();
            
            try {
            
                jugadoresCPU = cbd.buscarJugadoresTipo("CPU");
            
            } 
            catch (SQLException ex) {
            
                Logger.getLogger(VistaPrevia.class.getName()).log(Level.SEVERE, null, ex);
            
            }
            
            String[] arrayJugadoresCPU;
            
            arrayJugadoresCPU = jugadoresCPU.toArray(new String[100]);
            
            jugador1L.setListData(arrayJugadoresCPU);
            
            jugador2L.setListData(arrayJugadoresCPU);
            
            String[] arrayMedabots = new String[1];
            
            arrayMedabots[0] = "Version 1";
            
            DefaultComboBoxModel modeloMedabots = new DefaultComboBoxModel(arrayMedabots);
            
            medabotJ1.setModel(modeloMedabots);
            
            medabotJ2.setModel(modeloMedabots);
            
        }
        
    }//GEN-LAST:event_modoJuegoCBItemStateChanged

    public javax.swing.JList getJugador1L(){
        return this.jugador1L;
    }
    
    public javax.swing.JList getJugador2L(){
        return this.jugador2L;
    }
    
    public javax.swing.JComboBox getModoJuegoCB(){
        return this.modoJuegoCB;
    }
    
    public javax.swing.JComboBox getMedabotJ1(){
        return this.medabotJ1;
    }
    
    public javax.swing.JComboBox getMedabotJ2(){
        return this.medabotJ2;
    }
    
    public javax.swing.JButton getRobobatalla(){
        return this.robobatalla;
    }
    
    public javax.swing.JButton getVolver(){
        return this.volver;
    }
    
    public javax.swing.JButton getRecords(){
        return this.records;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JList jugador1L;
    private javax.swing.JScrollPane jugador1SP;
    private javax.swing.JList jugador2L;
    private javax.swing.JScrollPane jugador2SP;
    private javax.swing.JLabel jugadoresLabel;
    private javax.swing.JComboBox medabotJ1;
    private javax.swing.JComboBox medabotJ2;
    private javax.swing.JComboBox modoJuegoCB;
    private javax.swing.JLabel modoJuegoLabel;
    private javax.swing.JLabel queRobobatallaLabel;
    private javax.swing.JButton records;
    private javax.swing.JButton robobatalla;
    private javax.swing.JButton volver;
    // End of variables declaration//GEN-END:variables
}
